### ISSUE TITLE
Could you check that packages are loaded before running `autotest()` ?

### ISSUE THREAD

**Issue by statnmap** [ropensci-review-tools/autotest#47]
Function `rm_not_parseable()` removes code line with the function of the package that I tried to test with the following message:
![image](https://user-images.githubusercontent.com/21193866/124650649-3c201f00-de9a-11eb-9f9c-e7e28233e019.png)

This is because I did not loaded the package before running {autotest}
![image](https://user-images.githubusercontent.com/21193866/124650897-8dc8a980-de9a-11eb-92db-459e7a3f56fa.png)

If I run `pkgload::load_all()`, then the function is parseable.

I wonder if you can check this before running `autotest()` function, because there is no message at all if I run it in a fresh environment. 
![image](https://user-images.githubusercontent.com/21193866/124651308-07f92e00-de9b-11eb-8233-11abb6087e23.png)

I now can see that there is this information in the main vignette, but maybe you can at least add this information in the README.  
![image](https://user-images.githubusercontent.com/21193866/124651496-4989d900-de9b-11eb-8056-c8fb7213b5b7.png)

**Comment by statnmap** [comment]
Sorry. It seems this is not the problem.  
I run it twice and the second time nothing output.
Then, I run `roxygenise()`, and it worked again.  

I cannot reproduce though. So I'll close this issue and will open it again if I manage to get the source of the problem.

**Comment by mpadge** [comment]
Thanks @statnmap, glad the problem resolved itself! There's a [`preload_package()` function](https://github.com/ropensci-review-tools/autotest/blob/c615860fcfa0dffad7cb97fd7636fb48665db5d1/R/examples-to-yaml.R#L90-L127) that is called at the start of any `autotest` function, so all packages should be loaded.
