### ISSUE TITLE
Function name with underscore get changed to one with dot inside `extract_primary_call_content`

### ISSUE THREAD

**Issue by helske** [ropensci-review-tools/autotest#50]
I tried to run `autotest` on my `bssm` package and encountered following issue:

In my examples there is a line `system.time(particle_smoother(model, particles = 1000))`, and the function call `particle_smoother` gets changed into `particle.smoother` which results in an error:
```
> autotest_package()
* Extracting example code from 42 .Rd files
  |===================================================================================================================| 100%
v Extracted example code
Error in get(fun, mode = "function", envir = envir) : 
  object 'particle.smoother' of mode 'function' was not found
> traceback()
6: get(fun, mode = "function", envir = envir)
5: formals(fun = fn_name, envir = pkg_env)
4: assign_names_to_params(x_content, pkg)
3: one_ex_to_yaml(pkg = pkg_name, pkg_full = package, fn = this_fn, 
       rdname = rdname, x = xj, aliases = aliases, prev_fns = prev_fns)
2: examples_to_yaml(package, exclude = exclude, quiet = quiet)
1: autotest_package()
```

By debugging into `autotest` was able to locate that the issue seems to be caused inside `one_ex_to_yaml` which calls `extract_primary_call_content`. Here's is a minimal example:

```
extract_primary_call_content("a_b()", "a_b") # works
$a_b
   
"" 
```
Add parenthesis around the function call:
```
extract_primary_call_content("(a_b())", "a_b")
$a.b
   
"" 
```

I'm using `autotest_0.0.2.136`. Edit: Just installed the latest version from Github and the problem persists.

**Comment by mpadge** [comment]
Thanks @helske, that was because of this behaviour:

``` r
gsub ("\\\\.", "\\.", "particle\\_smoother")  
#> [1] "particle.smoother"
```

I don't feel so bad about having previously assumed that that would have not effect on `"\\_"`. But now i know, and have fixed. Thanks!

**Comment by helske** [comment]
Thanks, everything seems to work smoothly now! (Except apparently my package ;))

**Comment by mpadge** [comment]
@helske Note that running `autotest_package("bssm", test = TRUE)` may kill the entire R session on some systems. The solution to that will come via #17, which will prevent that happening, and instead return the information on what caused the problem. In your case it's calling `bootstrap_filter()` with `particles = .Machine$integer.max`. There is currently no control on that input parameter.

**Comment by helske** [comment]
Thanks, I noticed a sudden increase in memory and subsequent crash and guessed that there might be an issue with calling the SMC/MCMC functions with a huge number of particles/iterations. Unfortunately the definition of "huge" depends on various other parameters etc so I can't just add a simple sanity check for those (although `.Machine$integer.max` is of course always too much...). 

Marking some arguments non-testable or something would be nice although I can see it going against the main idea of the package if I start marking everything non-testable.

**Comment by mpadge** [comment]
It's actually really easy to make entire functions or single parameters non-testable, although admittedly not yet very well documented. The bigger problem is nevertheless illustrated by your package, for which there is no way to obtain the information on which parameter of which function is causing the fail. Until that's done, you can generate `x <- autotest_package(test=F)`, change the logical flags for the `test` column for any desired parameters to `FALSE`, and submit that whole thing as the extra `test_data` parameter. So in your case just set `x$test[x$fn_name = "bootstrap_filter" & x$parameter == "particles"] <- FALSE`, submit `x` as `test_data`, and test will be skipped. Hope that helps!
