### ISSUE TITLE
How to deal with ellipsis documentation?

### ISSUE THREAD

**Issue by christophsax** [ropensci-review-tools/autotest#57]
Some of my functions, e.g., [`ts_c`](https://www.tsbox.help/reference/ts_c.html), use `...` to collect any kind of time series object.

I have an example in the documentation:

```r
library(tsbox)
ts_c(mdeaths, fdeaths)
```

This works a bit like `c()`. But autotest complains about a parameter `NA` being undocumented. How to to deal with this situation?

```r
library(autotest)
a <- autotest_package(functions = "ts_c", test = TRUE)
a
#> # A tibble: 2 × 9
#>   type       test_name  fn_name parameter parameter_type operation content test 
#>   <chr>      <chr>      <chr>   <chr>     <chr>          <chr>     <chr>   <lgl>
#> 1 warning    par_is_do… ts_c    NA        NA             Check th… Exampl… TRUE 
#> 2 diagnostic vector_cu… ts_c    NA        vector         Custom c… Functi… TRUE 
```
Thanks a lot!

**Comment by mpadge** [comment]
Thanks Christoph! That one was at least easy to fix - `...` params are removed in pre-processing steps except when they are in the initial position. That commit just ensures they're not tested regardless.

**Comment by christophsax** [comment]
Thanks, Mark! Somehow, I still get an error about a missing `NA` parameter, but I don't see why. Here is a minimal example:

```r
#' Function that uses ...
#' 
#' @param ... stuff
#' @returns numeric, for now
#' @examples
#' c2(mdeaths, fdeaths)
#' @export
c2 <- function(...) {
  c(...)
}
```

```r
packageVersion("autotest")
# [1] ‘0.0.2.147’
```

```r
autotest_package(functions = "c2", test = TRUE)
# ✔ [1 / 1]: c2
# # A tibble: 1 × 9
#   type    test_name  fn_name parameter parameter_type operation   content  test 
#   <chr>   <chr>      <chr>   <chr>     <chr>          <chr>       <chr>    <lgl>
# 1 warning par_is_do… c2      NA        NA             Check that… Example… TRUE 
# # … with 1 more variable: yaml_hash <chr>
```

**Comment by mpadge** [comment]
Yeah, i saw that too, and thought it was because of your original `NA` function, but clearly can't be. I'll re-open and fix asap. Thanks

**Comment by mpadge** [comment]
With that commit i now see the expected `NULL` when testing `ts_c()`.

**Comment by christophsax** [comment]
I see the same, thanks Mark!
