### ISSUE TITLE
single_int_range(): keywords positive/negative only found under restrictive condition 

### ISSUE THREAD

**Issue by christophsax** [ropensci-review-tools/autotest#59]
The condition `length (rd_range) == 1` may be too restrictive:

https://github.com/ropensci-review-tools/autotest/blob/c75e23de60f44d09ef6a4225ab996d481c5fd02a/R/input-int.R#L99-L105

This requires the description to have exactly one number *and* the word `positive` in it.

Took me a while to figure out that this is accepted, but only because it contains a number (1) that is unrelated to the range:

```r
#' @param denominator positive number. Set equal to 1 if percentage change rate is
#'   given a decimal fraction
```

Without the 1, just writing `positive` still results in `Parameter [denominator] has no documented range`.

**Comment by mpadge** [comment]
Thanks @christophsax, totally agree. That commit simplifies the function, making the logic both clearer and better. It now basically lets anything through that greps "negative|positive", and only if not looks at the numbers given in the description, `rd_numbers`. If a finite integer range is identified it then does this (with messages simplified here for clarify):
```
if length(rd_numbers) == 0:
  message: "No documented range"
else if length(rd_numbers) == 1:
  message: "Only one limit identified; please specify both"
else if (abs(rd_numbers) >= abs(identified_range)):
  message: "Observed range exceeds documented values"
```

That seems to me far more consistent, but further opinions always appreciated. Thanks!
