### ISSUE TITLE
Not allowing substitution of logical with integer gives an error 

### ISSUE THREAD

**Issue by helske** [ropensci-review-tools/autotest#67]
I'm not sure if this is a bug or a design choice, but the `subst_int_for_logical ` test now complains if the function throws an error when the input for a single logical is replaced by an integer. That seems counterintuitive and contradictory to several other tests which assume explicit definitions of parameter types. The content actually says "Function call should still work unless explicitly prevented" which I understood to mean that either allow any integer, or throw an error if the value is not `TRUE` and `FALSE`.

I do see that it could be ok to allow 0L and 1L, but how is it to allowing say 2L feels potentially dangerous.

**Comment by mpadge** [comment]
Agreed and shall fix asap. Thanks as always for the constructive input!

**Comment by mpadge** [comment]
Thanks @helske - that one was my fault; just some poor code that didn't quite have the logical conditions correct. Great catch on your part; should now work as expected.
