### ISSUE TITLE
Trivial noise test is too strict

### ISSUE THREAD

**Issue by helske** [ropensci-review-tools/autotest#68]
In the trivial noise test, one of the failure conditions is

https://github.com/ropensci-review-tools/autotest/blob/3f0d2875ce22fb2b7e4701d42c7e4dc957b55c8c/R/input-double.R#L134-L135

where `res0 = f(x)`,  whereas `res1 = f(x + runif(length(x)) * 10 *  .Machine$double.eps)`. But this is quite a strict condition, for example
```
res0 <- 1^2
res1 <- (1 + 0.6 * 10 * .Machine$double.eps)^2 
max (abs (res0 - res1), na.rm = TRUE) > (10 * .Machine$double.eps)
[1] TRUE
```
I'm not sure what would be a good threshold though, as it depends on the function.

**Comment by mpadge** [comment]
Agreed it is very strict indeed. It might be better to multiply by 1e6 or so, which would still give a tolerance of around 1e-10 for most machines. Care to PR a modification to that?

**Comment by helske** [comment]
Yes I can do it, can you accept the previous one or can I just augment it with this (or should I create a new branch)?

**Comment by mpadge** [comment]
Please do a new one. I asked for a slight change on #64, and will merge as soon as that's done. Thanks!

**Comment by helske** [comment]
Ok, will do. But did you leave a comment on #64, as I don't see any?

**Comment by mpadge** [comment]
I started a review and requested your response, but maybe your notifications have blocked you seeing it? It was for line#170, and said:
> Great, thanks @helske, and thanks for adding yourself as ctb too - great to have you listed! Could you please just update the strsplit pattern from ",|, " to ",(\\s?)"? Then i'll happily merge.
