### ISSUE TITLE
Error in autotest-control vignette

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/autotest#80]
```r
Reading 'vignettes/autotest-control.Rmd'
-- RMarkdown error -------------------------------------------------------------
--------------------------------------------------------------------------------
Error in render_rmarkdown(pkg, input = input, output = output_file, output_format = format,  : 
  Failed to render RMarkdown
Caused by error:
! error in callr subprocess
Caused by error:
! object 'xt' not found
```

**Comment by maelle** [comment]
xt still seems used in a few places as the vignette can't build yet: https://ropensci.r-universe.dev/ui#builds

Thanks!

**Comment by mpadge** [comment]
Sorry about that! This whole pacakge is being rebuilt from scratch in `typetracer` branch, and i'm most ignoring `main` branch for the moment - thanks for catching that!

**Comment by mpadge** [comment]
[Stilll broken](https://github.com/ropensci-review-tools/autotest/runs/8202593370?check_suite_focus=true), but clearly an upstream problem that I'm not going to worry about for now.

**Comment by maelle** [comment]
could it be due to https://github.com/ropensci-review-tools/autotest/blob/37b588b951d9a4cc37be8aebf904c033ba9c0bbc/vignettes/autotest-control.Rmd#L6?

https://pkgdown.r-lib.org/reference/build_articles.html#output-formats

**Comment by mpadge** [comment]
oh yeah, likely indeed! One of the few glitches that sometimes pops up for non-RStudio users. I'll remove that and see what happens ...

**Comment by mpadge** [comment]
yep, all good - thank you so much @maelle!

**Comment by maelle** [comment]
yay! you're welcome!
